### ISSUE TITLE
sudachi_readingform doesn't support with ngram tokenizer

### ISSUE THREAD

**Issue by krrrr38** [WorksApplications/elasticsearch-sudachi#141]
## Problem

We try to use ngram tokenizer with `sudachi_readingform`. When creating index, elasticsearch raise `Attribute MorphemeAttribute was not present` error.

```sh
[2024-07-28T05:41:26,673][WARN ][r.suppressed             ] [xxx] path: /dummy, params: {pretty=true, index=dummy}
java.lang.IllegalStateException: Attribute MorphemeAttribute was not present
        at com.worksap.nlp.lucene.sudachi.ja.MorphemeFieldFilter.<init>(MorphemeFieldFilter.kt:92) ~[?:?]
        at com.worksap.nlp.lucene.sudachi.ja.SudachiReadingFormFilter.<init>(SudachiReadingFormFilter.kt:27) ~[?:?]
        at com.worksap.nlp.elasticsearch.sudachi.index.SudachiReadingFormFilterFactory.create(SudachiReadingFormFilterFactory.java:39) ~[?:?]
        at org.elasticsearch.index.analysis.CustomAnalyzer.createComponents(CustomAnalyzer.java:86) ~[elasticsearch-7.17.9.jar:7.17.9]
```

## Reproduce Steps

- Elasticsearch: 7.17.21
- setup elasticsearch-sudachi with following command

<details>
<summary>with elasticsearch-sudachi 3.2.2</summary>

```sh
bin/elasticsearch-plugin install https://github.com/WorksApplications/elasticsearch-sudachi/releases/download/v3.2.2/elasticsearch-7.17.21-analysis-sudachi-3.2.2.zip
curl -sLO https://d2ej7fkh96fzlu.cloudfront.net/sudachidict/sudachi-dictionary-latest-core.zip
unzip sudachi-dictionary-latest-core.zip
mkdir config/sudachi
cp sudachi-dictionary-*/system_core.dic config/sudachi/system_core.dic
```

</details>

- create index

<details>
<summary>using ngram tokenizer with sudachi_readingform</summary>

```sh
curl -i -XPUT -H "Content-Type: application/json" localhost:9200/dummy -d '
{
  "settings": {
    "analysis": {
      "tokenizer": {
        "ngram_tokenizer": {
          "type": "ngram",
          "token_chars": [ "letter", "digit" ],
          "min_gram": "2",
          "max_gram": "3"
        }
      },
      "filter": {
        "sudachi_readingform": {
          "type": "sudachi_readingform",
          "use_romaji": true
        }
      },
      "analyzer": {
        "romaji_analyzer": {
          "tokenizer": "ngram_tokenizer",
          "filter": [ "sudachi_readingform" ]
        }
      }
    }
  }
}'
HTTP/1.1 500 Internal Server Error
X-elastic-product: Elasticsearch
content-type: application/json; charset=UTF-8
content-length: 294

{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "Attribute MorphemeAttribute was not present"
      }
    ],
    "type" : "illegal_state_exception",
    "reason" : "Attribute MorphemeAttribute was not present"
  },
  "status" : 500
}
```
</details>

## Workaround

<details>
<summary>kuromoji_readingform allow to use ngram tokenizer. (not sure works correctly)</summary>

- install analysis-kuromoji
  - `bin/elasticsearch-plugin install analysis-kuromoji`
- create index

```sh
curl -i -XPUT -H "Content-Type: application/json" localhost:9200/dummy -d '
{
  "settings": {
    "analysis": {
      "tokenizer": {
        "ngram_tokenizer": {
          "type": "ngram",
          "token_chars": [ "letter", "digit" ],
          "min_gram": "2",
          "max_gram": "3"
        }
      },
      "filter": {
        "kuromoji_readingform": {
          "type": "kuromoji_readingform",
          "use_romaji": true
        }
      },
      "analyzer": {
        "romaji_analyzer": {
          "tokenizer": "ngram_tokenizer",
          "filter": [ "kuromoji_readingform" ]
        }
      }
    }
  }
}'
HTTP/1.1 200 OK
X-elastic-product: Elasticsearch
content-type: application/json; charset=UTF-8
content-length: 86

{
  "acknowledged" : true,
  "shards_acknowledged" : true,
  "index" : "dummy"
}
```

</details>

## In addition

If this usage is not expected one, please close this issue.

**Comment by krrrr38** [comment]
`ngram_tokenizer x kuromoji_readingform` also not works as intended, so close this issue.

----

- 🙅   sudachi_tokenizer x kuromoji_readingform

```sh
>  curl -s -XGET -H 'Content-Type: application/json' 'localhost:9200/wanted_1722114670023756000/_analyze?pretty=true' -d @analyze_wanted.json | head -10
{
  "tokens" : [
    {
      "token" : "先進",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "word",
      "position" : 0
    },
    {
```

- ✅  sudachi_tokenizer x sudach_readingform

```
> curl -s -XGET -H 'Content-Type: application/json' 'localhost:9200/wanted_1722114670023756000/_analyze?pretty=true' -d @analyze_wanted.json | head -10
{
  "tokens" : [
    {
      "token" : "センシン",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "word",
      "position" : 0
    },
    {
```

- 🙅  ngram_tokenizer x kuromoji_readingform

```
> curl -s -XGET -H 'Content-Type: application/json' 'localhost:9200/wanted_1722114670023756000/_analyze?pretty=true' -d @analyze_wanted.json | head -10
{
  "tokens" : [
    {
      "token" : "先進",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "word",
      "position" : 0
    },
    {
```
