### ISSUE TITLE
Latest Sudachi causes java.security.AccessControlException

### ISSUE THREAD

**Issue by miyakelp** [WorksApplications/elasticsearch-sudachi#36]
Elasticsearch crushed on `/_analyze` API using `elasticsearch-sudachi:v6.5.4-1.2.0` with latest `sudachi-1.2.0-SNAPSHOT`.
Maybe the cause is this commit.
https://github.com/WorksApplications/Sudachi/commit/001709baed7fd3f0e82bc1fed15d071007d301d3

Security permissions are required when open a dictionary.

Pull request : https://github.com/WorksApplications/elasticsearch-sudachi/pull/37

```
[2019-02-06T10:55:27,835][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [MCwJKXL] fatal error in thread [elasticsearch[MCwJKXL][analyze][T#1]], exiting
java.lang.ExceptionInInitializerError: null
        at com.worksap.nlp.sudachi.DictionaryFactory.create(DictionaryFactory.java:56) ~[?:?]
        at com.worksap.nlp.lucene.sudachi.ja.SudachiTokenizer.<init>(SudachiTokenizer.java:89) ~[?:?]
        at com.worksap.nlp.lucene.sudachi.ja.SudachiTokenizer.<init>(SudachiTokenizer.java:79) ~[?:?]
        at com.worksap.nlp.elasticsearch.sudachi.index.SudachiTokenizerFactory.create(SudachiTokenizerFactory.java:68) ~[?:?]
        at org.elasticsearch.index.analysis.CustomAnalyzer.createComponents(CustomAnalyzer.java:89) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:134) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:196) ~[lucene-core-7.5.0.jar:7.5.0 b5bf70b7e32d7ddd9742cc821d471c5fabd4e3df - jimczi - 2018-09-18 13:01:13]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.simpleAnalyze(TransportAnalyzeAction.java:259) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.analyze(TransportAnalyzeAction.java:244) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:165) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.action.admin.indices.analyze.TransportAnalyzeAction.shardOperation(TransportAnalyzeAction.java:81) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$1.doRun(TransportSingleShardAction.java:112) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) ~[elasticsearch-6.5.4.jar:6.5.4]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-6.5.4.jar:6.5.4]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.misc")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
        at java.security.AccessController.checkPermission(AccessController.java:895) ~[?:?]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:322) ~[?:?]
        at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1290) ~[?:?]
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:896) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:315) ~[?:?]
        at com.worksap.nlp.sudachi.JapaneseDictionary.<clinit>(JapaneseDictionary.java:223) ~[?:?]
        ... 17 more
```

**Comment by hiroshi-matsuda** [comment]
We've released fixed version. Thanks again!
