### ISSUE TITLE
Failed to launch on elasticsearch 7.6 and 7.7 when system_core.dic doesn't exist

### ISSUE THREAD

**Issue by ciffelia** [WorksApplications/elasticsearch-sudachi#59]
# Description
On elasticsearch 7.6 and 7.7, elasticsearch fails to launch when `elasticsearch-sudachi` is installed but `config/sudachi/system_core.dic` doesn't exist.

# Expected behavior
Elasticsearch starts successfully even if `system_core.dic` doesn't exist. Dictionary files are required only when creating and using an index that uses `analysis-sudachi` analyzer.

# Version

- elasticsearch-sudachi 2.0.1
- Elasticsearch 7.6.2 and 7.7.0 (on Docker)
- Docker on Windows 2.3.0.3 (Docker Engine 19.03.8)

# Steps to reproduce
## Elasticsearch 7.5.2 (works)

```sh
# Launch a container
> docker run -it --rm --env discovery.type=single-node --env bootstrap.memory_lock=true docker.elastic.co/elasticsearch/elasticsearch:7.5.2 sh
# Install elasticsearch-sudachi
> elasticsearch-plugin install https://github.com/WorksApplications/elasticsearch-sudachi/releases/download/v7.5.2-2.0.1/analysis-sudachi-elasticsearch7.5-2.0.1.zip
# Launch elasticsearch
> /usr/local/bin/docker-entrypoint.sh
...
{"type": "server", ..., "message": "loaded plugin [analysis-sudachi]" }
...
{"type": "server", ..., "message": "Active license is now [BASIC]; ...",  ...  }
```

## Elasticsearch 7.6.2 (fails)

```sh
# Launch a container
> docker run -it --rm --env discovery.type=single-node --env bootstrap.memory_lock=true docker.elastic.co/elasticsearch/elasticsearch:7.6.2 sh
# Install elasticsearch-sudachi
> elasticsearch-plugin install https://github.com/WorksApplications/elasticsearch-sudachi/releases/download/v7.6.2-2.0.1/analysis-sudachi-elasticsearch7.6-2.0.1.zip
# Launch elasticsearch
> /usr/local/bin/docker-entrypoint.sh
...
{"type": "server", ..., "message": "loaded plugin [analysis-sudachi]" }
...
{"type": "server", "timestamp": "...", "level": "ERROR", "component": "o.e.x.c.t.IndexTemplateRegistry", "cluster.name": "docker-cluster", "node.name": "...",
"message": "error adding index template [ilm-history] from [/ilm-history.json] for [index_lifecycle]",
"cluster.uuid": "...", "node.id": "..." ,
"stacktrace": ["java.io.UncheckedIOException: java.io.FileNotFoundException: /usr/share/elasticsearch/config/sudachi/system_core.dic (No such file or directory)",
"at com.worksap.nlp.lucene.sudachi.ja.SudachiAnalyzer.createComponents(SudachiAnalyzer.java:93) ~[?:?]",
"at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:136) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]",
"at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:199) ~[lucene-core-8.5.1.jar:8.5.1 edb9fc409398f2c3446883f9f80595c884d245d0 - ivera - 2020-04-08 08:55:42]",
"at org.elasticsearch.index.analysis.AnalysisRegistry.checkVersions(AnalysisRegistry.java:649) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.analysis.AnalysisRegistry.produceAnalyzer(AnalysisRegistry.java:613) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:532) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:218) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:428) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:611) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:549) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService.validateTemplate(MetaDataIndexTemplateService.java:404) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService.access$300(MetaDataIndexTemplateService.java:73) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.metadata.MetaDataIndexTemplateService$4.execute(MetaDataIndexTemplateService.java:301) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:47) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.7.0.jar:7.7.0]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]",
"Caused by: java.io.FileNotFoundException: /usr/share/elasticsearch/config/sudachi/system_core.dic (No such file or directory)",
"at java.io.FileInputStream.open0(Native Method) ~[?:?]",
"at java.io.FileInputStream.open(FileInputStream.java:212) ~[?:?]",
"at java.io.FileInputStream.<init>(FileInputStream.java:154) ~[?:?]",
"at java.io.FileInputStream.<init>(FileInputStream.java:109) ~[?:?]",
"at com.worksap.nlp.sudachi.MMap.map(MMap.java:52) ~[?:?]",
"at com.worksap.nlp.sudachi.dictionary.BinaryDictionary.<init>(BinaryDictionary.java:33) ~[?:?]",
"at com.worksap.nlp.sudachi.dictionary.BinaryDictionary.readSystemDictionary(BinaryDictionary.java:54) ~[?:?]",
"at com.worksap.nlp.sudachi.JapaneseDictionary.readSystemDictionary(JapaneseDictionary.java:106) ~[?:?]",
"at com.worksap.nlp.sudachi.JapaneseDictionary.<init>(JapaneseDictionary.java:56) ~[?:?]",
"at com.worksap.nlp.sudachi.DictionaryFactory.create(DictionaryFactory.java:62) ~[?:?]",
"at com.worksap.nlp.lucene.sudachi.ja.SudachiTokenizer.<init>(SudachiTokenizer.java:75) ~[?:?]",
"at com.worksap.nlp.lucene.sudachi.ja.SudachiTokenizer.<init>(SudachiTokenizer.java:65) ~[?:?]",
"at com.worksap.nlp.lucene.sudachi.ja.SudachiAnalyzer.createComponents(SudachiAnalyzer.java:91) ~[?:?]",
"... 26 more"] }

```

**Comment by kazuma-t** [comment]
Did you download and install the system dictionary?
https://github.com/WorksApplications/elasticsearch-sudachi#installation

**Comment by ciffelia** [comment]
No, but I think I don't need it unless i create an index that uses `sudachi_tokenizer`.

**Comment by kazuma-t** [comment]
If installed, it may be the same as this.
https://sudachi-dev.slack.com/archives/CBCF278AC/p1583801791027400

In conclusion, due to limitations of Elasticsearch, we must always put the core dictionary file in `es_config/sudachi/system_core.dic`.

**Comment by ciffelia** [comment]
I see. Thanks!
