### ISSUE TITLE
インデックス作成時にエラーが二種類が発生する

### ISSUE THREAD

**Issue by miu200521358** [WorksApplications/elasticsearch-sudachi#77]
はじめまして。素晴らしい開発をありがとうございます。
Sudachiをインストールしてからインデックスを作成しようとした時にエラーが発生しましたのでご報告させていただきます。

# 環境

Ubuntu 18.04 LTS（WSL2)
Java: OpenJDK 8
Elasticsearch: 7.7.0

# エラーログ

```
[2021-08-27T05:04:43,668][WARN ][r.suppressed             ] [els-node-1] path: /test_sudachi01, params: {index=test_sudachi01}
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.misc")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
        at java.security.AccessController.checkPermission(AccessController.java:1036) ~[?:?]
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:408) ~[?:?]
        at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1376) ~[?:?]
```

# 対応

セキュリティポリシーを追加
pluginフォルダ配下に置いても読み込まれない（？）ようだったので、起動時のオプションとして指定しました。

/etc/elasticsearch/jvm.options.d/security.options

```
-Djava.security.policy=/etc/elasticsearch/jvm.options.d/els.policy
```

/etc/elasticsearch/jvm.options.d/els.policy
elasticsearchのデフォルトポリシーに最下部二行を追加しています。

```
/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0 and the Server Side Public License, v 1; you may not use this file except
 * in compliance with, at your election, the Elastic License 2.0 or the Server
 * Side Public License, v 1.
 */

// Default security policy file.
// On startup, BootStrap reads environment and adds additional permissions
// for configured paths and network binding to these.

//// SecurityManager impl:
//// Must have all permissions to properly perform access checks

grant codeBase "${codebase.elasticsearch-secure-sm}" {
  permission java.security.AllPermission;
};

//// Elasticsearch core:
//// These are only allowed inside the server jar, not in plugins
grant codeBase "${codebase.elasticsearch}" {
  // needed for loading plugins which may expect the context class loader to be set
  permission java.lang.RuntimePermission "setContextClassLoader";
};

//// Very special jar permissions:
//// These are dangerous permissions that we don't want to grant to everything.

grant codeBase "${codebase.lucene-core}" {
  // needed to allow MMapDirectory's "unmap hack" (die unmap hack, die)
  // java 8 package
  permission java.lang.RuntimePermission "accessClassInPackage.sun.misc";
  // java 9 "package"
  permission java.lang.RuntimePermission "accessClassInPackage.jdk.internal.ref";
  permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
  // NOTE: also needed for RAMUsageEstimator size calculations
  permission java.lang.RuntimePermission "accessDeclaredMembers";
};

grant codeBase "${codebase.lucene-misc}" {
  // needed to allow shard shrinking to use hard-links if possible via lucenes HardlinkCopyDirectoryWrapper
  permission java.nio.file.LinkPermission "hard";
};

grant codeBase "${codebase.elasticsearch-plugin-classloader}" {
  // needed to create the classloader which allows plugins to extend other plugins
  permission java.lang.RuntimePermission "createClassLoader";
};

grant codeBase "${codebase.jna}" {
  // for registering native methods
  permission java.lang.RuntimePermission "accessDeclaredMembers";
};

//// Everything else:

grant {
  // needed by vendored Guice
  permission java.lang.RuntimePermission "accessClassInPackage.jdk.internal.vm.annotation";

  // checked by scripting engines, and before hacks and other issues in
  // third party code, to safeguard these against unprivileged code like scripts.
  permission org.elasticsearch.SpecialPermission;

  // Allow host/ip name service lookups
  permission java.net.SocketPermission "*", "resolve";

  // Allow reading and setting socket keepalive options
  permission jdk.net.NetworkPermission "getOption.TCP_KEEPIDLE";
  permission jdk.net.NetworkPermission "setOption.TCP_KEEPIDLE";
  permission jdk.net.NetworkPermission "getOption.TCP_KEEPINTERVAL";
  permission jdk.net.NetworkPermission "setOption.TCP_KEEPINTERVAL";
  permission jdk.net.NetworkPermission "getOption.TCP_KEEPCOUNT";
  permission jdk.net.NetworkPermission "setOption.TCP_KEEPCOUNT";

  // Allow read access to all system properties
  permission java.util.PropertyPermission "*", "read";

  // TODO: clean all these property writes up, and don't allow any more in. these are all bogus!

  // LuceneTestCase randomization (locale/timezone/cpus/ssd)
  // TODO: put these in doPrivileged and move these to test-framework.policy
  permission java.util.PropertyPermission "user.language", "write";
  permission java.util.PropertyPermission "user.timezone", "write";
  permission java.util.PropertyPermission "lucene.cms.override_core_count", "write";
  permission java.util.PropertyPermission "lucene.cms.override_spins", "write";
  // messiness in LuceneTestCase: do the above, or clean this up, or simply allow to fail if its denied
  permission java.util.PropertyPermission "solr.solr.home", "write";
  permission java.util.PropertyPermission "solr.data.dir", "write";
  permission java.util.PropertyPermission "solr.directoryFactory", "write";

  // set by ESTestCase to improve test reproducibility
  // TODO: set this with gradle or some other way that repros with seed?
  permission java.util.PropertyPermission "processors.override", "write";

  // TODO: these simply trigger a noisy warning if its unable to clear the properties
  // fix that in randomizedtesting
  permission java.util.PropertyPermission "junit4.childvm.count", "write";
  permission java.util.PropertyPermission "junit4.childvm.id", "write";

  // needed by Settings
  permission java.lang.RuntimePermission "getenv.*";

  // thread permission for the same thread group and ancestor groups
  // (this logic is more strict than the JDK, see SecureSM)
  permission java.lang.RuntimePermission "modifyThread";
  permission java.lang.RuntimePermission "modifyThreadGroup";

  // needed by ExceptionSerializationTests and RestTestCase for
  // some hackish things they do. otherwise only needed by groovy
  // (TODO: clean this up?)
  permission java.lang.RuntimePermission "getProtectionDomain";

  // needed by HotThreads and potentially more
  // otherwise can be provided only to test libraries
  permission java.lang.RuntimePermission "getStackTrace";

  // needed by JMX instead of getFileSystemAttributes, seems like a bug...
  permission java.lang.RuntimePermission "getFileStoreAttributes";

  // needed for jimfs and NewPathForShardsTests
  // otherwise can be provided only to test libraries
  permission java.lang.RuntimePermission "fileSystemProvider";

  // needed by jvminfo for monitoring the jvm
  permission java.lang.management.ManagementPermission "monitor";

  // needed by JDKESLoggerTests
  permission java.util.logging.LoggingPermission "control";

  // load averages on Linux
  permission java.io.FilePermission "/proc/loadavg", "read";

  // read max virtual memory areas
  permission java.io.FilePermission "/proc/sys/vm/max_map_count", "read";

  // OS release on Linux
  permission java.io.FilePermission "/etc/os-release", "read";
  permission java.io.FilePermission "/usr/lib/os-release", "read";
  permission java.io.FilePermission "/etc/system-release", "read";

  // io stats on Linux
  permission java.io.FilePermission "/proc/self/mountinfo", "read";
  permission java.io.FilePermission "/proc/diskstats", "read";

  // control group stats on Linux
  permission java.io.FilePermission "/proc/self/cgroup", "read";
  permission java.io.FilePermission "/sys/fs/cgroup/cpu", "read";
  permission java.io.FilePermission "/sys/fs/cgroup/cpu/-", "read";
  permission java.io.FilePermission "/sys/fs/cgroup/cpuacct", "read";
  permission java.io.FilePermission "/sys/fs/cgroup/cpuacct/-", "read";
  permission java.io.FilePermission "/sys/fs/cgroup/memory", "read";
  permission java.io.FilePermission "/sys/fs/cgroup/memory/-", "read";

  // system memory on Linux systems affected by JDK bug (#66629)
  permission java.io.FilePermission "/proc/meminfo", "read";

  // 2021/08/27
  permission java.lang.RuntimePermission "*";
  permission java.lang.reflect.ReflectPermission "*";
};
```

また、辞書にアクセスできるようになった後、sudachi-dictionary-20210802-core.zipを読み込もうとすると、「invalid dictionary」が発生しました。

```
[2021-08-27T06:22:14,163][WARN ][r.suppressed             ] [els-node-1] path: /test_sudachi02, params: {index=test_sudachi02}
java.io.UncheckedIOException: java.io.IOException: invalid dictionary
Caused by: java.io.IOException: invalid dictionary
        at com.worksap.nlp.sudachi.dictionary.BinaryDictionary.<init>(BinaryDictionary.java:47) ~[?:?]
        at com.worksap.nlp.sudachi.dictionary.BinaryDictionary.readSystemDictionary(BinaryDictionary.java:54) ~[?:?]
        at com.worksap.nlp.sudachi.JapaneseDictionary.readSystemDictionary(JapaneseDictionary.java:106) ~[?:?]
```

sudachi-dictionary-20190425-core.zip　ですと正常に辞書が読み込まれ、インデックスを作成することが出来ました。

sudachi-dictionary-20210802-core
![image](https://user-images.githubusercontent.com/38824651/131042912-72320376-8ee9-413c-9025-3de7de5498a2.png)

sudachi-dictionary-20190425-core
![image](https://user-images.githubusercontent.com/38824651/131043018-d4ed1217-5f5b-4054-b304-f6c52db253da.png)

バイナリエディタでヘッダを比較すると冒頭が違っているようなので、何か変わっているのかもしれません。
お手数をおかけして申し訳ありませんが、ご確認の程、よろしくお願いいたします。

**Comment by kazuma-t** [comment]
ご報告ありがとうございます。
辞書などのリソースの配置は $ES_CONFIG 以下でないとセキュリティ上エラーにするというのが Elasticsearch の方針のようです。
`invalid dictionary` のエラーの方ですが、辞書フォーマットは何度か変更しており古い Sudachi ではあたらしい 辞書はよめなくなっています。あたらしいプラグインを利用していただくか、プラグインに同梱している Sudachi の JAR ファイルを最新のものと入れ替えると動くのではないかとおもいます。
https://github.com/WorksApplications/Sudachi/releases/tag/v0.5.2

**Comment by kazuma-t** [comment]
7.7.0 向けの最新版のプラグインはリリースしていませんが、`es7.4-7.7` ブランチからビルドできます。
```
$ ./gradlew -PelasticsearchVersion=7.7.0 build
```

**Comment by miu200521358** [comment]
お返事ありがとうございます。
エラーの詳細、対応策について了解しました。
ブランチの場所もありがとうございます。
ブランチからビルドして最新版の辞書を試してみます。
